sudo: required

language: python

branches:
  only:
  - master

git:
  submodules:
    false

before_install:
  - echo -e "machine bitbucket.org\n  login $BITBUCKET_USER_NAME\n  password $BITBUCKET_USER_PASSWORD" >~/.netrc
  - chmod a+x ./submodules.sh
  - ./submodules.sh
  # - "ls -al"
  # - "pwd"
  # - "ls -al ~/"

install:
    - "cd test-travis-ci"
    - python setup.py install

script:
    - "cd test-travis-ci"
    - python -m pytest -v

stages:
    - name: static analysis
    - name: test

jobs:
  fast_finish: true
  include:
    - stage: static analysis
      python: "2.7"

    - stage: test
      python: "3.5"
